// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_prod.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmqgGAvdJ8tRynGspab0372RG_MBvbxVo',
    appId: '1:966128666735:web:ddd18bab83d27cd171259a',
    messagingSenderId: '966128666735',
    projectId: 'quocalc-504218',
    authDomain: 'quocalc-504218.firebaseapp.com',
    storageBucket: 'quocalc-504218.firebasestorage.app',
    measurementId: 'G-56LFS6KRFG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeXJrA9g3Gw4sHr-YlZ2Ig1V2eZRfryR8',
    appId: '1:966128666735:android:9e6c0209b224f69271259a',
    messagingSenderId: '966128666735',
    projectId: 'quocalc-504218',
    storageBucket: 'quocalc-504218.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrSqf6YEYlIQiZ01QXqZ99w2ZMThI6eIc',
    appId: '1:966128666735:ios:4b2d9221fb4ba9ec71259a',
    messagingSenderId: '966128666735',
    projectId: 'quocalc-504218',
    storageBucket: 'quocalc-504218.firebasestorage.app',
    iosBundleId: 'com.example.qoutaCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmqgGAvdJ8tRynGspab0372RG_MBvbxVo',
    appId: '1:966128666735:web:1ab65cc4cb41aeba71259a',
    messagingSenderId: '966128666735',
    projectId: 'quocalc-504218',
    authDomain: 'quocalc-504218.firebaseapp.com',
    storageBucket: 'quocalc-504218.firebasestorage.app',
    measurementId: 'G-PY35HECK7R',
  );
}
