// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_dev.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCzmETaeDP4OSm-Td5VlKMhClCSQq4KYvY',
    appId: '1:229982416333:web:ff5fdf54cc2f296ebbe884',
    messagingSenderId: '229982416333',
    projectId: 'quocalc-dev',
    authDomain: 'quocalc-dev.firebaseapp.com',
    storageBucket: 'quocalc-dev.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlJJLJh9MaKrfbAIG0lqq0kmtclUQTAZI',
    appId: '1:229982416333:android:45206307794c333cbbe884',
    messagingSenderId: '229982416333',
    projectId: 'quocalc-dev',
    storageBucket: 'quocalc-dev.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAYWkhIfuqx79Sm9ngZcXoVJWdsYgP2Dxg',
    appId: '1:229982416333:ios:7b737d64c45218e7bbe884',
    messagingSenderId: '229982416333',
    projectId: 'quocalc-dev',
    storageBucket: 'quocalc-dev.firebasestorage.app',
    iosBundleId: 'com.example.qoutaCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCzmETaeDP4OSm-Td5VlKMhClCSQq4KYvY',
    appId: '1:229982416333:web:eedc31734c061939bbe884',
    messagingSenderId: '229982416333',
    projectId: 'quocalc-dev',
    authDomain: 'quocalc-dev.firebaseapp.com',
    storageBucket: 'quocalc-dev.firebasestorage.app',
  );
}
