// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiLfkrlkoxCROKq4I1EFb0C-nu2U72Ybg',
    appId: '1:823258124820:web:2461674bbcc738a1d64d01',
    messagingSenderId: '823258124820',
    projectId: 'quocalc-staging',
    authDomain: 'quocalc-staging.firebaseapp.com',
    storageBucket: 'quocalc-staging.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQXELfMocok0_Qas1ISaRisa28mN7kYWY',
    appId: '1:823258124820:android:a8a5e99ebe22bcc0d64d01',
    messagingSenderId: '823258124820',
    projectId: 'quocalc-staging',
    storageBucket: 'quocalc-staging.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAjRHAu8hSlGbgRRo-qTxQLW9xHydl-orY',
    appId: '1:823258124820:ios:acf868324aa4a7b8d64d01',
    messagingSenderId: '823258124820',
    projectId: 'quocalc-staging',
    storageBucket: 'quocalc-staging.firebasestorage.app',
    iosBundleId: 'com.example.qoutaCalculator',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDiLfkrlkoxCROKq4I1EFb0C-nu2U72Ybg',
    appId: '1:823258124820:web:8545ddc89162dbedd64d01',
    messagingSenderId: '823258124820',
    projectId: 'quocalc-staging',
    authDomain: 'quocalc-staging.firebaseapp.com',
    storageBucket: 'quocalc-staging.firebasestorage.app',
  );
}
